### ISSUE TITLE
cannot even install it

### ISSUE THREAD

**Issue by mark0237** [xvrdm/ricv#2] opened 2022-03-25 17:41 UTC
i cannot install it

> devtools::install("xvrdm/ricv")
Error: [ENOENT] Failed to realize 'xvrdm/ricv': no such file or directory

**Comment by mark0237** [comment] 2022-03-25 19:44
I got to install it, but how I can handle images within the R enviroment? Should I set a working direcctory and the images shall be there? O where? thank you

**Comment by xvrdm** [comment] 2022-03-28 15:11
Hi @mark0237, sorry for the trouble.

I made a mistake and wrote the `renv` command. Thanks for the flag @jebyrnes: will update the doc tonight.

Regarding your second question, I am unsure what you call an "image within the R environment". Are you referring to plot objects for example? If so, they will have to be saved to disk first. There is a first PR to make this action seamless for ggplot2 plots: once it is done, we can add more types of images.

**Comment by jebyrnes** [comment] 2022-03-28 15:40
I wonder if the issue is that, within R itself, even with images output, the viewer (in RStudio anyway) won't show the images. You have to put them in RMarkdown or Shiny in order to see the package work. At least in my experience.

**Comment by xvrdm** [comment] 2022-03-28 17:48
@jebyrnes It depends. The RStudio Viewer works if you give full urls of resources served by a http server to img1/2. 

```r
ricv(
  img1="https://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Gull_portrait_ca_usa.jpg/1280px-Gull_portrait_ca_usa.jpg", 
  img2="https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/Schachfiguren%2C_Bauern_--_2022_--_0022_%28bw%29.jpg/1920px-Schachfiguren%2C_Bauern_--_2022_--_0022_%28bw%29.jpg"
)
```

seems to work. 

I haven´t found a way yet to make the RStudio Viewer work on local files, without launching an http server on the machine.

**Comment by mark0237** [comment] 2022-03-29 00:15
thank you, now I understand how to use it.

 I wanted to do it on local files, but I will find a way

thanks

**Comment by xvrdm** [comment] 2022-03-29 09:23
Ok thanks, closing for now.

**Closed by xvrdm** 2022-03-29 09:23 UTC
